eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8000/eureka/ #配置注册中心地址
spring:
  application:
    name: shop-gateway
server:
  port: 9000
zuul:
  routes:
    shop-cate-api:
      path: /cates/**
    shop-goods-api:
      path: /goods/**
    shop-member-api:
      path: /members/**
    shop-cart-api:
      path: /carts/**
fh:
  shop:
    checkUrls: /api/carts/findCart,/api/carts/addCartItem,/api/carts/findCart
